### ISSUE TITLE
Add support for decoding raw data

### ISSUE THREAD

**Issue by jhthorsen** [dgl/protocol-redis-xs#4]
Hello, and thank you for your work on this module.

I was wondering if you could add support for decoding binary data?

I'm trying to read/write data serialised with Storable in my module [Mojo::Redis::Cache](https://github.com/jhthorsen/mojo-redis/blob/master/lib/Mojo/Redis/Cache.pm), but I have to use Protocol::Redis for this, instead of your module.

I can reproduce the bug by running the following test in my project below:

```
TEST_XS=1 MOJO_REDIS_DEBUG=1 TEST_ONLINE=redis://localhost prove -vl t/cache.t
```

Omitting `TEST_XS=1` makes the test successful.

**Comment by Grinnz** [comment]
Fixed by #2
