### ISSUE TITLE
Add support for nested multi bulk replies with depth > 2

### ISSUE THREAD

**Issue by jhthorsen** [dgl/protocol-redis-xs#5]
I got a bug report in my project Mojo::Redis, which I cannot fix.

It's regarding reading the response from the [stream](https://redis.io/topics/streams-intro) commands. the problem is that the nesting is higher than what is supported by this module.

I'm not even sure why you have a max depth "guard" and why it is so low.

Please see https://github.com/jhthorsen/mojo-redis/issues/34 for more details.

**Comment by Grinnz** [comment]
This is a limitation of hiredis itself. The hiredis bundled here is 0.10.1, but in 0.11.0 the nesting limit was increased to 7. https://github.com/redis/hiredis/commit/51ab89d8998e3f6844f72e020e53200e80fe52f7

**Comment by Grinnz** [comment]
Resolved in #6.
