### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by eserte** [dgl/protocol-redis-xs#7]
See http://fast-matrix.cpantesters.org/?dist=Protocol-Redis-XS%200.06;reports=1#sl=7,1 for an overview. It is possible that Protocol::Redis 1.0010 has something to do with the failure (at least a lot of fails were generated after the release date of Protocol-Redis-1.0010), but statistical analysis is not very clear about it (R² is not 1).

**Comment by Grinnz** [comment]
This should be fixed by Protocol::Redis 1.0011. Thanks for the report!
